# vi: set numberwidth=2 :
# vi: set tabstop=2 :
# vi: set shiftwidth=2 :

---
  - name: Copy sshd_config
    copy: src=roles/security/files/sshd_config dest=/etc/ssh/sshd_config

  - name: Install unattended-upgrades
    apt: name=unattended-upgrades state=present

  - name: Install fail2ban
    apt: pkg=fail2ban state=installed

  - name: Install UFW
    apt: pkg=ufw state=installed

  - name: Enable UFW
    ufw: state=enabled

  - name: UFW deny incoming
    ufw: policy=deny direction=incoming

  - name: UFW deny outgoing
    ufw: policy=deny direction=outgoing

  - name: UFW allow ssh
    ufw: rule=allow name=ssh

  - name: UFW rate limit ssh
    ufw: rule=limit name=ssh

  - name: Configure other UFW ports
    ufw: rule=allow port={{ item.port }} proto={{ item.proto }} direction={{ item.direction }}
    with_items: "{{ ufw_ports }}"
